### ISSUE TITLE
求助大佬自选股变量

### ISSUE THREAD

**Issue by KIclF4** [leafxcy/JavaScript#5]
## 开始执行... 2021-11-29 15:49:13

/ql/config/env.sh: line 13: syntax error near unexpected token `('
/ql/config/env.sh: line 13: `export TxStockAppHeader="TxStockAppHeader='{"Host":"wzq.tenpay.com","Accept":"*/*","Connection":"keep-alive","Cookie":"pgv_info=ssid=s484.....;pgv_pvid=348.....;ts_last=/activity/page/welwareCenter/;ts_refer=zqact.tenpay.com/;ts_sid=78065.....;ts_uid=260.....4","User-Agent":"Mozilla/5.0(iPhone;CPUiPhoneOS15_0likeMacOSX)AppleWebKit/605.1.15(KHTML,likeGecko)Mobile/15E148qqstock/9.6.0deviceType/iphone","Accept-Language":"zh-CN,zh-Hans;q=0.9","Referer":"https://wzq.tenpay.com/activity/page/welwareCenter/","Accept-Encoding":"gzip,deflate,br"}'"'

🔔腾讯自选股, 开始!
未找到环境变量:  TxStockAppHeader TxStockWxHeader

写了环境变量出现上面的错误提示，应该怎么设置

**Comment by jizeguo** [comment]
TxStockAppHeader="TxStockAppHeader='{"
你这很显然变量名粘了2个

**Comment by KIclF4** [comment]
> TxStockAppHeader="TxStockAppHeader='{" 你这很显然变量名粘了2个
我去改掉了也还是报错

## 开始执行... 2021-11-29 21:41:35

/ql/config/env.sh: line 13: syntax error near unexpected token `('
/ql/config/env.sh: line 13: `export TxStockAppHeader="'{"Host":"wzq.tenpay.com","Accept":"*/*","Connection":"keep-alive","Cookie":"pgv_info=ssid=s4848266800;pgv_pvid=3486536868;ts_last=/activity/page/welwareCenter/;ts_refer=zqact.tenpay.com/;ts_sid=7806508218

**Comment by jizeguo** [comment]
你的这个引号怎么这么多
我的就是这样：
![image](https://user-images.githubusercontent.com/7609667/143970183-eb1b1f6d-6ec5-4d1a-a7b2-4dd4f04d1d17.png)
